#case1
#FROM almalinux:8
#ARG username
#RUN adduser $username
#USER $username
#CMD ["sleep","100"]

FROM almalinux:8
ARG username
RUN adduser $username
USER $username
ARG COURSE
ARG TRAINER
RUN echo "course=${COURSE}, trainer=${TRAINER}"
ENV COURSE=${COURSE}
ENV TRAINER=${KEYVALUE}
CMD ["sleep","100"]
