FROM almalinux:8
RUN yum install nginx -y
RUN rm -rf /usr/share/nginx/html/index.html
COPY index.html /usr/share/nginx/html/
ADD  https://github.com/daws-76s/notes/blob/master/demo-session.txt /tmp/
CMD ["nginx","-g","daemon off;"]